from .model import ChessPiece

data = [
    ChessPiece("pawn_b1", "pawn_black", "black", 9),
    ChessPiece("pawn_b2", "pawn_black", "black", 10),
    ChessPiece("pawn_b3", "pawn_black", "black", 11),
    ChessPiece("pawn_b4", "pawn_black", "black", 12),
    ChessPiece("pawn_b5", "pawn_black", "black", 13),
    ChessPiece("pawn_b6", "pawn_black", "black", 14),
    ChessPiece("pawn_b7", "pawn_black", "black", 15),
    ChessPiece("pawn_b8", "pawn_black", "black", 16),
    ChessPiece("pawn_w1", "pawn_white", "white", 49),
    ChessPiece("pawn_w2", "pawn_white", "white", 50),
    ChessPiece("pawn_w3", "pawn_white", "white", 51),
    ChessPiece("pawn_w4", "pawn_white", "white", 52),
    ChessPiece("pawn_w5", "pawn_white", "white", 53),
    ChessPiece("pawn_w6", "pawn_white", "white", 54),
    ChessPiece("pawn_w7", "pawn_white", "white", 55),
    ChessPiece("pawn_w8", "pawn_white", "white", 56),
    ChessPiece("bishop_b1", "bishop_black", "black", 3),
    ChessPiece("bishop_b2", "bishop_black", "black", 6),
    ChessPiece("bishop_w1", "bishop_white", "white", 59),
    ChessPiece("bishop_w2", "bishop_white", "white", 62),
    ChessPiece("king_b", "king_black", "black", 5),
    ChessPiece("king_w", "king_white", "white", 61),
    ChessPiece("queen_b", "queen_black", "black", 4),
    ChessPiece("queen_w", "queen_white", "white", 60),
    ChessPiece("knight_b1", "knight_black", "black", 2),
    ChessPiece("knight_b2", "knight_black", "black", 7),
    ChessPiece("knight_w1", "knight_white", "white", 58),
    ChessPiece("knight_w2", "knight_white", "white", 63),
    ChessPiece("rook_b1", "rook_black", "black", 1),
    ChessPiece("rook_b2", "rook_black", "black", 8),
    ChessPiece("rook_w1", "rook_white", "white", 57),
    ChessPiece("rook_w2", "rook_white", "white", 64),
]
