"""guest models

Revision ID: 90cf5e5ffdf8
Revises: 5e0d56cd5f12
Create Date: 2025-03-14 17:18:12.896725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cf5e5ffdf8'
down_revision: Union[str, None] = '5e0d56cd5f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_created_at'), 'guest', ['created_at'], unique=False)
    op.create_index(op.f('ix_guest_id'), 'guest', ['id'], unique=True)
    op.create_index(op.f('ix_guest_username'), 'guest', ['username'], unique=True)
    op.create_table('offline_game_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_game_session_created_at'), 'offline_game_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_offline_game_session_id'), 'offline_game_session', ['id'], unique=False)
    op.create_index(op.f('ix_offline_game_session_time'), 'offline_game_session', ['time'], unique=False)
    op.create_table('guest_game_session',
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('offline_game_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['offline_game_session_id'], ['offline_game_session.id'], ),
    sa.PrimaryKeyConstraint('guest_id', 'offline_game_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_game_session')
    op.drop_index(op.f('ix_offline_game_session_time'), table_name='offline_game_session')
    op.drop_index(op.f('ix_offline_game_session_id'), table_name='offline_game_session')
    op.drop_index(op.f('ix_offline_game_session_created_at'), table_name='offline_game_session')
    op.drop_table('offline_game_session')
    op.drop_index(op.f('ix_guest_username'), table_name='guest')
    op.drop_index(op.f('ix_guest_id'), table_name='guest')
    op.drop_index(op.f('ix_guest_created_at'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
