"""guest session

Revision ID: a67e9bd50b12
Revises: 
Create Date: 2025-03-15 11:48:57.616726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67e9bd50b12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_session_created_at'), 'game_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_game_session_id'), 'game_session', ['id'], unique=False)
    op.create_index(op.f('ix_game_session_time'), 'game_session', ['time'], unique=False)
    op.create_table('guest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_created_at'), 'guest', ['created_at'], unique=False)
    op.create_index(op.f('ix_guest_id'), 'guest', ['id'], unique=True)
    op.create_index(op.f('ix_guest_username'), 'guest', ['username'], unique=True)
    op.create_table('offline_game_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_game_session_created_at'), 'offline_game_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_offline_game_session_id'), 'offline_game_session', ['id'], unique=False)
    op.create_index(op.f('ix_offline_game_session_time'), 'offline_game_session', ['time'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('gest_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id')
    )
    op.create_index(op.f('ix_gest_session_created_at'), 'gest_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_gest_session_id'), 'gest_session', ['id'], unique=False)
    op.create_index(op.f('ix_gest_session_value'), 'gest_session', ['value'], unique=True)
    op.create_table('guest_game_session',
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('offline_game_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['offline_game_session_id'], ['offline_game_session.id'], ),
    sa.PrimaryKeyConstraint('guest_id', 'offline_game_session_id')
    )
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('loss', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistic_id'), 'statistic', ['id'], unique=False)
    op.create_index(op.f('ix_statistic_loss'), 'statistic', ['loss'], unique=False)
    op.create_index(op.f('ix_statistic_win'), 'statistic', ['win'], unique=False)
    op.create_table('user_game_session',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_session')
    op.drop_index(op.f('ix_statistic_win'), table_name='statistic')
    op.drop_index(op.f('ix_statistic_loss'), table_name='statistic')
    op.drop_index(op.f('ix_statistic_id'), table_name='statistic')
    op.drop_table('statistic')
    op.drop_table('guest_game_session')
    op.drop_index(op.f('ix_gest_session_value'), table_name='gest_session')
    op.drop_index(op.f('ix_gest_session_id'), table_name='gest_session')
    op.drop_index(op.f('ix_gest_session_created_at'), table_name='gest_session')
    op.drop_table('gest_session')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_offline_game_session_time'), table_name='offline_game_session')
    op.drop_index(op.f('ix_offline_game_session_id'), table_name='offline_game_session')
    op.drop_index(op.f('ix_offline_game_session_created_at'), table_name='offline_game_session')
    op.drop_table('offline_game_session')
    op.drop_index(op.f('ix_guest_username'), table_name='guest')
    op.drop_index(op.f('ix_guest_id'), table_name='guest')
    op.drop_index(op.f('ix_guest_created_at'), table_name='guest')
    op.drop_table('guest')
    op.drop_index(op.f('ix_game_session_time'), table_name='game_session')
    op.drop_index(op.f('ix_game_session_id'), table_name='game_session')
    op.drop_index(op.f('ix_game_session_created_at'), table_name='game_session')
    op.drop_table('game_session')
    # ### end Alembic commands ###
